image: golang:latest

stages:
  - test
  - build

go_fmt:
  stage: test
  script:
    - go fmt

go_vet:
  stage: test
  script:
    - go vet -c 3

build_golang_1_12_5:
  stage: build
  image: golang:1.12.5-stretch
  script:
    - go build .