image: golang:latest

before_script:
  - mkdir bin
stages:
  - test
  - build

go_fmt:
  stage: test
  script:
    - go fmt

go_vet:
  stage: test
  script:
    - go vet -c 3

build_linked:
  stage: build
  image: golang:1.12.5-stretch
  script:
    - go build -o bin/froyg -ldflags "-X main.version=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" .
  artifacts:
    paths:
      - bin/*
    expire_in: 1 day
