image: img.101c0d3.run/citruspi/go_xc_img:1.12.5-stretch

before_script:
  - mkdir bin
stages:
  - test
  - build
  - xcompile

go_fmt:
  stage: test
  script:
    - go fmt

go_vet:
  stage: test
  script:
    - go vet -c 3

build:
  stage: build
  script:
    - go build -o bin/froyg -ldflags "-X main.version=$CI_COMMIT_SHA" .

.xcompile:
  stage: xcompile
  script:
    - export label="froyg-$CI_COMMIT_REF_SLUG-$GOOS.$GOARCH"
    - rm -rf $label
    - mkdir $label
    - go build -o $label/froyg -ldflags "-w -X main.version=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" .
    - cp LICENSE $label/
    - tar cfJ $label.tar.xf $label
  artifacts:
    paths:
      - "*.tar.xf"
    expire_in: 1 day

linux_386:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=386

linux_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=amd64

linux_arm:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=arm

linux_arm64:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=arm64

darwin_386:
  extends: .xcompile
  before_script:
    - export GOOS=darwin
    - export GOARCH=386

darwin_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=darwin
    - export GOARCH=amd64

windows_386:
  extends: .xcompile
  before_script:
    - export GOOS=windows
    - export GOARCH=386

windows_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=windows
    - export GOARCH=amd64

dragonfly_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=dragonfly
    - export GOARCH=amd64

freebsd_386:
  extends: .xcompile
  before_script:
    - export GOOS=freebsd
    - export GOARCH=386

freebsd_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=freebsd
    - export GOARCH=amd64

freebsd_arm:
  extends: .xcompile
  before_script:
    - export GOOS=freebsd
    - export GOARCH=arm

netbsd_386:
  extends: .xcompile
  before_script:
    - export GOOS=netbsd
    - export GOARCH=386

netbsd_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=netbsd
    - export GOARCH=amd64

netbsd_arm:
  extends: .xcompile
  before_script:
    - export GOOS=netbsd
    - export GOARCH=arm

openbsd_386:
  extends: .xcompile
  before_script:
    - export GOOS=openbsd
    - export GOARCH=386

openbsd_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=openbsd
    - export GOARCH=amd64

openbsd_arm:
  extends: .xcompile
  before_script:
    - export GOOS=openbsd
    - export GOARCH=arm