image: golang:1.9.3-alpine3.7

stages:
  - build

compile:
  stage: build
  before_script:
    - apk update
    - apk add git
    - go get github.com/aws/aws-sdk-go/...
  script:
    - go build main.go

