image: golang:1.12.5-stretch

before_script:
  - mkdir bin
stages:
  - test
  - build
  - xcompile

go_fmt:
  stage: test
  script:
    - go fmt

go_vet:
  stage: test
  script:
    - go vet -c 3

build:
  stage: build
  script:
    - go build -o bin/froyg -ldflags "-X main.version=$CI_COMMIT_SHA" .
  artifacts:
    paths:
      - bin/*
    expire_in: 1 day

.xcompile:
  stage: xcompile
  script:
    - go build -o bin/froyg.$GOOS.$GOARCH -ldflags "-w -X main.version=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" .
  artifacts:
    paths:
      - bin/*
    expire_in: 1 day

xcompile_linux_386_linked:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=386

xcompile_linux_amd64_linked:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=amd64

xcompile_linux_arm_linked:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=arm

xcompile_linux_arm64_linked:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=arm64


xcompile_darwin_386_linked:
  extends: .xcompile
  before_script:
    - export GOOS=darwin
    - export GOARCH=386

xcompile_darwin_amd64_linked:
  extends: .xcompile
  before_script:
    - export GOOS=darwin
    - export GOARCH=amd64

xcompile_darwin_arm_linked:
  extends: .xcompile
  before_script:
    - export GOOS=darwin
    - export GOARCH=arm

xcompile_darwin_arm64_linked:
  extends: .xcompile
  before_script:
    - export GOOS=darwin
    - export GOARCH=arm64
