image: img.doom.fm/citruspi/go_xc:1.13.6-stretch

before_script:
  - mkdir bin
stages:
  - test
  - compile
  - package
  - release

fmt:
  stage: test
  script:
    - go fmt

vet:
  stage: test
  script:
    - go vet -c 3

.xcompile:
  stage: compile
  needs:
    - fmt
    - vet
  script:
    - mkdir out
    - go build -o "out/froyg-$GOOS.$GOARCH$XLABEL" $XFLAGS $TAGS -ldflags "-w $XLDFLAGS -X main.version=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" .
  artifacts:
    paths:
      - out
    expire_in: 1 day

linux_386:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=386

linux_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=amd64

linux_amd64_static:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=amd64
    - export CGO_ENABLED=0
    - export XFLAGS="-a"
    - export XLABEL="-static"
    - export TAGS="-tags netgo"
    - export XLDFLAGS='-extldflags "-static"'

linux_arm:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=arm

linux_arm64:
  extends: .xcompile
  before_script:
    - export GOOS=linux
    - export GOARCH=arm64

darwin_386:
  extends: .xcompile
  before_script:
    - export GOOS=darwin
    - export GOARCH=386

darwin_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=darwin
    - export GOARCH=amd64

windows_386:
  extends: .xcompile
  before_script:
    - export GOOS=windows
    - export GOARCH=386

windows_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=windows
    - export GOARCH=amd64

dragonfly_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=dragonfly
    - export GOARCH=amd64

freebsd_386:
  extends: .xcompile
  before_script:
    - export GOOS=freebsd
    - export GOARCH=386

freebsd_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=freebsd
    - export GOARCH=amd64

freebsd_arm:
  extends: .xcompile
  before_script:
    - export GOOS=freebsd
    - export GOARCH=arm

netbsd_386:
  extends: .xcompile
  before_script:
    - export GOOS=netbsd
    - export GOARCH=386

netbsd_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=netbsd
    - export GOARCH=amd64

netbsd_arm:
  extends: .xcompile
  before_script:
    - export GOOS=netbsd
    - export GOARCH=arm

openbsd_386:
  extends: .xcompile
  before_script:
    - export GOOS=openbsd
    - export GOARCH=386

openbsd_amd64:
  extends: .xcompile
  before_script:
    - export GOOS=openbsd
    - export GOARCH=amd64

openbsd_arm:
  extends: .xcompile
  before_script:
    - export GOOS=openbsd
    - export GOARCH=arm

tarballs:
  stage: package
  image:
    name: debian:buster
  before_script:
    - apt-get update && apt-get install -y xz-utils
  script:
    - bash .ci/pkg-tarballs.sh
  artifacts:
    expire_in: 1 day
    paths:
      - tarballs

.linux-packages:
  stage: package
  script:
    - export NAME="froyg"
    - export DESCRIPTION="Multi-region, multi-bucket HTTP Gateway for S3 Objects"
    - export MAINTAINER="Mihir Singh (@citruspi)"
    - export LICENSE="Public Domain"
    - export URL="https://src.doom.fm/citruspi/froyg"
    - export OUT="packages/froyg-$ARCH.$TYPE"
    - mkdir packages
    - bash .ci/pkg-native.sh out/froyg-linux.$ARCH=/usr/bin/froyg
  artifacts:
    paths:
      - packages
    expire_in: 1 day

deb_amd64:
  extends: .linux-packages
  needs:
    - linux_amd64
  image:
    name: img.doom.fm/build/fpm:1.11.0-debian-buster
  before_script:
    - export TYPE=deb
    - export ARCH=amd64

deb_386:
  extends: .linux-packages
  needs:
    - linux_386
  image:
    name: img.doom.fm/build/fpm:1.11.0-debian-buster
  before_script:
    - export TYPE=deb
    - export ARCH=386

rpm_amd64:
  extends: .linux-packages
  needs:
    - linux_amd64
  image:
    name: img.doom.fm/build/fpm:1.11.0-centos-7
  before_script:
    - export TYPE=rpm
    - export ARCH=amd64

rpm_386:
  extends: .linux-packages
  needs:
    - linux_386
  image:
    name: img.doom.fm/build/fpm:1.11.0-centos-7
  before_script:
    - export TYPE=rpm
    - export ARCH=386

publish:
  stage: release
  needs:
    - tarballs
    - deb_amd64
    - deb_386
    - rpm_amd64
    - rpm_386
  script:
    - publish
  only:
    - tags