image: img.doom.fm/build/golang:latest-1.14.5-buster

stages:
  - test
  - compile
  - package
  - release

include:
  - project: build/gitlab
    ref: master
    file: golang/test.yml
  - project: build/gitlab
    ref: master
    file: golang/compile.yml
  - project: build/gitlab
    ref: master
    file: golang/pkg-tarballs.yml
  - project: build/gitlab
    ref: master
    file: golang/pkg-native.yml

publish:
  stage: release
  needs:
    - tarballs
    - deb_amd64
    - deb_386
    - rpm_amd64
    - rpm_386
  script:
    - publish
  only:
    - tags