image: img.doom.fm/build/golang:latest-1.14.5-buster

stages:
  - test
  - compile
  - package
  - release

include:
  - project: build/gitlab
    ref: master
    file: golang/test.yml
  - project: build/gitlab
    ref: master
    file: golang/compile.yml
  - project: build/gitlab
    ref: master
    file: golang/pkg-tarballs.yml
  - project: build/gitlab
    ref: master
    file: golang/pkg-native.yml

publish:
  stage: release
  needs:
    - tar_linux_386
    - tar_linux_amd64
    - tar_linux_amd64_static
    - tar_linux_arm
    - tar_linux_arm64
    - tar_darwin_386
    - tar_darwin_amd64
    - tar_windows_386
    - tar_windows_amd64
    - tar_dragonfly_amd64
    - tar_freebsd_386
    - tar_freebsd_amd64
    - tar_freebsd_arm
    - tar_netbsd_386
    - tar_netbsd_amd64
    - tar_netbsd_arm
    - tar_openbsd_386
    - tar_openbsd_amd64
    - tar_openbsd_arm
    - deb_amd64
    - deb_386
    - rpm_amd64
    - rpm_386
  script:
    - publish
  only:
    - tags