stages:
  - prerequisites
  - compile
  - package

variables:
  TARGET: all
  PACKAGE: apk-all deb-all rpm-all tar-all zip-all
  GO_VERSION: "1.16.6"

include:
  - project: build/pipelines/golang
    ref: dev/match-rust
    file: prerequisites.yml
  - project: build/pipelines/golang
    ref: dev/match-rust
    file: compile.yml
  - project: build/pipelines/golang
    ref: dev/match-rust
    file: package.yml
